### ISSUE TITLE
Requires app restart as of MX 7.8.0

### ISSUE THREAD

**Issue by JelleDekker** [mendix/generator-mendix#29]
Just tried to create a new widget in Mx 7.8.0, using the generator and the boilerplate. After having updated the app from 5 to 6 to 7.8, I notice that just running gulp and pressing F5 in the browser is no longer enough. Now you also need to restart the app via the modeler to see any JS changes.

**Comment by JelteMX** [comment]
Could you check whether or not you have an issue with your deployment folder?

I am fairly certain this has to do with a folder it cannot find, or being unwritable (there can be issues regarding file permissions). What happens if you:

1. stop Gulp
2. stop application, clean deployment folder
3. run the application
4. then run Gulp
5. make a change to the widget to propagate the changes

I use the same principle in Mendix 7.8.0 and it works perfectly fine. No changes have been made to how the deployment folder is structured. Also, 'bundle widgets' is not on by any chance?

**Comment by JelleDekker** [comment]
Hmm your right. Seems somewhere in the update from 5 to 6 to 7 the folders became read-only. It's working now.
