### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by tomko80** [mendix/generator-mendix#30]
Running the _yo mendix_ reported some deprecated dependencies like graceful and minimatch, these seem not to be compatible with the current version of nodejs.

What should I do?

**Comment by tomko80** [comment]
Could you also maybe consider updating the test project to Mendix 6 or even 7?

**Comment by JelteMX** [comment]
Yes and no.

The deprecated dependencies should not be a problem. If you use Node 8.x.x it will automatically install the compatible dependencies. Some of the dependencies might appear deprecated, but still work fine. I will update the dependencies later on, have to check which ones work.

As for the test-project, I consider that one deprecated. I can update it to Mendix 6, but for building widgets it's better to just create your own test-project instead of using the test-project in this repository.

**Comment by tomko80** [comment]
Thanks for the input!

Could you refer me to some docs or add some guidance for how to configure the gulp/grunt auto build to work with my own test project? The youtube video that pointed me here only mentioned this topic...

**Comment by JelteMX** [comment]
We still lack documentation on this part, partly due to the fact I haven't found the time for it. I have shortly summarized it in the README, see [Gulp](https://github.com/mendix/generator-mendix#gulp-1) section. Basically what you do is point the path to your own test-project and it will automatically push the mpk to the widgets folder and your changes to the deployment folder.

**Comment by tomko80** [comment]
I think its excellent work you have done. Helps novices like me to get started :)
Hope Mendix can arrange you time to work on this.

**Comment by JelteMX** [comment]
Documentation will be added soon. Closing the issue.
